/**
 * themes.ts — 5 built-in presentation themes. Each theme is a flat map of
 * CSS custom properties consumed by every component via `var(--c-*)`.
 */

export interface Theme {
  id: string;
  name: string;
  desc: string;
  swatch: [string, string, string];
  dark: boolean;
  vars: Record<string, string>;
}

const SHARED_KEYS = [
  "--c-bg", "--c-bg2", "--c-body", "--c-body2", "--c-panel", "--c-panel-edge",
  "--c-display-bg", "--c-display-bg2", "--c-display-edge", "--c-text",
  "--c-text-dim", "--c-accent", "--c-accent2", "--c-btn", "--c-btn-edge",
  "--c-btn-text", "--c-fn", "--c-fn-text", "--c-op", "--c-op-text",
  "--c-eq", "--c-eq-text", "--c-shift", "--c-alpha", "--c-border",
  "--c-soft", "--c-soft2", "--c-card-border", "--c-ring",
  "--c-display-text", "--c-display-text-dim",
];

export const THEMES: Theme[] = [
  {
    id: "hardware",
    name: "Classic Textbook",
    desc: "Clean off-white page with deep charcoal slate text and professional muted-blue accents",
    swatch: ["#f8fafc", "#e2e8f0", "#1e3a8a"],
    dark: false,
    vars: {
      "--c-bg": "#f8fafc",
      "--c-bg2": "#f1f5f9",
      "--c-body": "#ffffff",
      "--c-body2": "#f1f5f9",
      "--c-panel": "#ffffff",
      "--c-panel-edge": "#cbd5e1",
      "--c-display-bg": "#f1f5f9",
      "--c-display-bg2": "#e2e8f0",
      "--c-display-edge": "#cbd5e1",
      "--c-text": "#0f172a",
      "--c-text-dim": "#475569",
      "--c-display-text": "#0f172a",
      "--c-display-text-dim": "#475569",
      "--c-accent": "#2563eb",
      "--c-accent2": "#1e3a8a",
      "--c-btn": "#ffffff",
      "--c-btn-edge": "#cbd5e1",
      "--c-btn-text": "#0f172a",
      "--c-fn": "#e2e8f0",
      "--c-fn-text": "#0f172a",
      "--c-op": "#e2e8f0",
      "--c-op-text": "#0f172a",
      "--c-eq": "#15803d",
      "--c-eq-text": "#ffffff",
      "--c-shift": "#d97706",
      "--c-alpha": "#dc2626",
      "--c-border": "#cbd5e1",
      "--c-soft": "#ffffff",
      "--c-soft2": "#f1f5f9",
      "--c-card-border": "#cbd5e1",
      "--c-ring": "#2563eb",
    },
  },
  {
    id: "midnight",
    name: "Midnight Study",
    desc: "Deep warm obsidian-navy base with soft white typography and clean blue-gray control frames",
    swatch: ["#0f172a", "#1e293b", "#38bdf8"],
    dark: true,
    vars: {
      "--c-bg": "#0f172a",
      "--c-bg2": "#1e293b",
      "--c-body": "#1e293b",
      "--c-body2": "#0f172a",
      "--c-panel": "#1e293b",
      "--c-panel-edge": "#334155",
      "--c-display-bg": "#1e293b",
      "--c-display-bg2": "#0f172a",
      "--c-display-edge": "#334155",
      "--c-text": "#f8fafc",
      "--c-text-dim": "#94a3b8",
      "--c-display-text": "#f8fafc",
      "--c-display-text-dim": "#64748b",
      "--c-accent": "#38bdf8",
      "--c-accent2": "#0ea5e9",
      "--c-btn": "#334155",
      "--c-btn-edge": "#1e293b",
      "--c-btn-text": "#f8fafc",
      "--c-fn": "#475569",
      "--c-fn-text": "#f8fafc",
      "--c-op": "#475569",
      "--c-op-text": "#f8fafc",
      "--c-eq": "#38bdf8",
      "--c-eq-text": "#0f172a",
      "--c-shift": "#f59e0b",
      "--c-alpha": "#ef4444",
      "--c-border": "#334155",
      "--c-soft": "#1e293b",
      "--c-soft2": "#334155",
      "--c-card-border": "#334155",
      "--c-ring": "#38bdf8",
    },
  },
  {
    id: "rose",
    name: "Blush & Berry",
    desc: "Soft pastel-pink backdrop with deep maroon text indicators and white workspace cards",
    swatch: ["#fff1f2", "#db2777", "#ffffff"],
    dark: false,
    vars: {
      "--c-bg": "#fff1f2",
      "--c-bg2": "#ffe4e6",
      "--c-body": "#ffffff",
      "--c-body2": "#ffe4e6",
      "--c-panel": "#ffffff",
      "--c-panel-edge": "#fecdd3",
      "--c-display-bg": "#fff1f2",
      "--c-display-bg2": "#ffe4e6",
      "--c-display-edge": "#fecdd3",
      "--c-text": "#4c0519",
      "--c-text-dim": "#9f1239",
      "--c-display-text": "#4c0519",
      "--c-display-text-dim": "#be185d",
      "--c-accent": "#db2777",
      "--c-accent2": "#be185d",
      "--c-btn": "#ffffff",
      "--c-btn-edge": "#fecdd3",
      "--c-btn-text": "#4c0519",
      "--c-fn": "#fbcfe8",
      "--c-fn-text": "#9d174d",
      "--c-op": "#fbcfe8",
      "--c-op-text": "#9d174d",
      "--c-eq": "#db2777",
      "--c-eq-text": "#ffffff",
      "--c-shift": "#b45309",
      "--c-alpha": "#e11d48",
      "--c-border": "#fecdd3",
      "--c-soft": "#ffffff",
      "--c-soft2": "#fff1f2",
      "--c-card-border": "#ffe4e6",
      "--c-ring": "#db2777",
    },
  },
  {
    id: "mint",
    name: "Mint Cream",
    desc: "Calming pale sage-green foundation with soft forest-green headings and elements",
    swatch: ["#f0fdf4", "#16a34a", "#14532d"],
    dark: false,
    vars: {
      "--c-bg": "#f0fdf4",
      "--c-bg2": "#dcfce7",
      "--c-body": "#ffffff",
      "--c-body2": "#dcfce7",
      "--c-panel": "#ffffff",
      "--c-panel-edge": "#bbf7d0",
      "--c-display-bg": "#f0fdf4",
      "--c-display-bg2": "#dcfce7",
      "--c-display-edge": "#bbf7d0",
      "--c-text": "#14532d",
      "--c-text-dim": "#16a34a",
      "--c-display-text": "#14532d",
      "--c-display-text-dim": "#16a34a",
      "--c-accent": "#16a34a",
      "--c-accent2": "#15803d",
      "--c-btn": "#ffffff",
      "--c-btn-edge": "#bbf7d0",
      "--c-btn-text": "#14532d",
      "--c-fn": "#dcfce7",
      "--c-fn-text": "#15803d",
      "--c-op": "#dcfce7",
      "--c-op-text": "#15803d",
      "--c-eq": "#16a34a",
      "--c-eq-text": "#ffffff",
      "--c-shift": "#d97706",
      "--c-alpha": "#dc2626",
      "--c-border": "#bbf7d0",
      "--c-soft": "#ffffff",
      "--c-soft2": "#dcfce7",
      "--c-card-border": "#bbf7d0",
      "--c-ring": "#16a34a",
    },
  },
  {
    id: "highcontrast",
    name: "High-Contrast Exam",
    desc: "Stark white outline style on black background engineered for low-light or color-blind accessibility",
    swatch: ["#000000", "#ffffff", "#ffffff"],
    dark: true,
    vars: {
      "--c-bg": "#000000",
      "--c-bg2": "#121212",
      "--c-body": "#000000",
      "--c-body2": "#121212",
      "--c-panel": "#000000",
      "--c-panel-edge": "#ffffff",
      "--c-display-bg": "#000000",
      "--c-display-bg2": "#121212",
      "--c-display-edge": "#ffffff",
      "--c-text": "#ffffff",
      "--c-text-dim": "#d1d5db",
      "--c-display-text": "#ffffff",
      "--c-display-text-dim": "#9ca3af",
      "--c-accent": "#ffffff",
      "--c-accent2": "#ffffff",
      "--c-btn": "#121212",
      "--c-btn-edge": "#ffffff",
      "--c-btn-text": "#ffffff",
      "--c-fn": "#000000",
      "--c-fn-text": "#ffffff",
      "--c-op": "#000000",
      "--c-op-text": "#ffffff",
      "--c-eq": "#ffffff",
      "--c-eq-text": "#000000",
      "--c-shift": "#ffffff",
      "--c-alpha": "#ffffff",
      "--c-border": "#ffffff",
      "--c-soft": "#000000",
      "--c-soft2": "#121212",
      "--c-card-border": "#ffffff",
      "--c-ring": "#ffffff",
    },
  },
];

export function themeById(id: string): Theme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}

export function themeVars(theme: Theme): React.CSSProperties {
  const v: Record<string, string> = {};
  for (const k of SHARED_KEYS) {
    v[k] = theme.vars[k] ?? (
      k === "--c-display-text" ? theme.vars["--c-text"] :
      k === "--c-display-text-dim" ? theme.vars["--c-text-dim"] :
      ""
    );
  }
  return v as React.CSSProperties;
}

export { SHARED_KEYS };
